server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db_prize_range
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    datasource-initialization: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

file:
  name: "movielist.csv"
  header: "year;title;studios;producers;winner"